[gamevals.dbtable]
pets = 65400
cats = 65401
pet_morphs = 65402
dogs = 65403
pet_drops = 65404
pet_skilling = 65405

[gamevals.enum]
pet_insurance_pets = 985
pet_categories = 65400
cat_colours = 65401
cat_stages = 65402
cat_catch_chances = 65403
heron_pet_chance = 65404
rock_golem_chance = 65405
beaver_chance = 65406

[gamevals.varp]
pet_follower_state = 65473
pet_emote_cooldown = 65474
pet_morph_unlocks = 65478
cat_growth = 65477
cat_care = 65476
dog_growth = 65475

[gamevals.varbit]
pet_beaver_funky_log = 65420
pet_beaver_fox = 65421
pet_beaver_pheasant = 65422
pet_muphin_forms = 65423
pet_nid_rax = 65424
pet_lil_zik_morphs = 65425
pet_phoenix_blue = 65426
pet_phoenix_green = 65427
pet_phoenix_purple = 65428
pet_phoenix_white = 65429
pet_gull_gulliver = 65430
pet_gull_fish_fed = 65431
pet_olmlet_morphs = 65432
cat_growth_events = 65433
cat_growth_ticks = 65434
cat_rats_caught = 65435
cat_original_colour = 65436
cat_strokes = 65437
cat_hunger = 65438
cat_attention = 65439
cat_medal_given = 65440
dog_growth_events = 65441
dog_growth_ticks = 65442
dog_fed_ticks = 65443
pet_follower_stuck = 65444
pet_emote_index = 65445
pet_follower_busy = 65446

[gamevals.dbrow]
pet_abyssalsire_pet = 62000
pet_madangelpet = 62001
pet_molepet = 62002
pet_molepet_naked = 62003
pet_dukesucelluspet = 62004
pet_rtbrandapet = 62005
pet_rteldricpet = 62006
pet_cowbosspet = 62007
pet_vardorvispet = 62008
pet_callisto_pet = 62009
pet_callisto_pet_legacy = 62010
pet_dompet = 62011
pet_gryphonbosspet = 62012
pet_gryphonbosspet_adult = 62013
pet_hell_pet = 62014
pet_hueypet = 62015
pet_hydrapet = 62016
pet_hydrapet_electric = 62017
pet_hydrapet_fire = 62018
pet_hydrapet_extinguished = 62019
pet_infernopet = 62020
pet_infernopet_zuk = 62021
pet_kqpet_walking = 62022
pet_kqpet_flying = 62023
pet_verzikpet = 62024
pet_maidenpet = 62025
pet_bloatpet = 62026
pet_nylocaspet = 62027
pet_sotetsegpet = 62028
pet_xarpuspet = 62029
pet_leviathanpet = 62030
pet_nightmarepet = 62031
pet_nightmarepet_parasite = 62032
pet_maggotkingpet = 62033
pet_amoxliatlpet = 62034
pet_muspahpet = 62035
pet_muspahpet_melee = 62036
pet_muspahpet_shielded = 62037
pet_nexpet = 62038
pet_araxxorpet = 62039
pet_araxxorpet_cute = 62040
pet_dawnpet = 62041
pet_duskpet = 62042
pet_olmpet = 62043
pet_dogadilepet = 62044
pet_tektonpet = 62045
pet_tektonenragedpet = 62046
pet_vanguardpet = 62047
pet_vasapet = 62048
pet_vespulapet = 62049
pet_vespulaflyingpet = 62050
pet_chaoselepet = 62051
pet_primepet = 62052
pet_rexpet = 62053
pet_supremepet = 62054
pet_corepet = 62055
pet_corppet = 62056
pet_bandospet = 62057
pet_zamorakpet = 62058
pet_krakenpet = 62059
pet_armadylpet = 62060
pet_smokepet = 62061
pet_smokepet_old = 62062
pet_snakepet = 62063
pet_snakepet_blue = 62064
pet_snakepet_orange = 62065
pet_saradominpet = 62066
pet_phoenixpet = 62067
pet_phoenixpet_blue = 62068
pet_phoenixpet_green = 62069
pet_phoenixpet_purple = 62070
pet_phoenixpet_white = 62071
pet_kbdpet = 62072
pet_scorpia_pet = 62073
pet_scurriuspet = 62074
pet_skotizopet = 62075
pet_zalcanopet = 62076
pet_solhereditpet = 62077
pet_sarachnispet = 62078
pet_sarachnispet_blue = 62079
pet_sarachnispet_orange = 62080
pet_temporosspet = 62081
pet_wardenpet_tumeken = 62082
pet_wardenpet_elidinis = 62083
pet_wardenpet_tumeken_destroyed = 62084
pet_wardenpet_elidinis_destroyed = 62085
pet_wardenpet_akkha = 62086
pet_wardenpet_baba = 62087
pet_wardenpet_kephri = 62088
pet_wardenpet_zebak = 62089
pet_jad_pet = 62090
pet_jad_pet_inferno = 62091
pet_venenatis_pet = 62092
pet_venenatis_pet_legacy = 62093
pet_vetion_pet = 62094
pet_vetion_pet2 = 62095
pet_vetion_pet_legacy = 62096
pet_vetion_pet2_legacy = 62097
pet_vorkathpet = 62098
pet_whispererpet = 62099
pet_yamapet = 62100
pet_gauntletpet = 62101
pet_gauntletpet_corrupt = 62102
pet_skillpethunter_grey = 62103
pet_skillpethunter_red = 62104
pet_skillpethunter_black = 62105
pet_skillpethunter_gold = 62106
pet_skillpetwc = 62107
pet_skillpet_wc_oak = 62108
pet_skillpet_wc_willow = 62109
pet_skillpet_wc_maple = 62110
pet_skillpet_wc_yew = 62111
pet_skillpet_wc_magic = 62112
pet_skillpet_wc_redwood = 62113
pet_skillpet_wc_teak = 62114
pet_skillpet_wc_mahogany = 62115
pet_skillpet_wc_arctic = 62116
pet_skillpet_wc_camphor = 62117
pet_skillpet_wc_ironwood = 62118
pet_skillpet_wc_jatoba = 62119
pet_skillpet_wc_rosewood = 62120
pet_skillpet_wc_fox = 62121
pet_skillpet_wc_pheasant = 62122
pet_skillpetagility = 62123
pet_skillpetagility_dark = 62124
pet_skillpetagility_bone = 62125
pet_skillpetfish = 62126
pet_skillpetfish_tempoross = 62127
pet_skillpetrunecrafting_fire = 62128
pet_skillpetrunecrafting_air = 62129
pet_skillpetrunecrafting_mind = 62130
pet_skillpetrunecrafting_water = 62131
pet_skillpetrunecrafting_earth = 62132
pet_skillpetrunecrafting_body = 62133
pet_skillpetrunecrafting_cosmic = 62134
pet_skillpetrunecrafting_chaos = 62135
pet_skillpetrunecrafting_nature = 62136
pet_skillpetrunecrafting_law = 62137
pet_skillpetrunecrafting_death = 62138
pet_skillpetrunecrafting_soul = 62139
pet_skillpetrunecrafting_astral = 62140
pet_skillpetrunecrafting_blood = 62141
pet_skillpetrunecrafting_wrath = 62142
pet_skillpetrunecrafting_gotr = 62143
pet_skillpetmining = 62144
pet_skillpetmining_tin = 62145
pet_skillpetmining_copper = 62146
pet_skillpetmining_iron = 62147
pet_skillpetmining_blurite = 62148
pet_skillpetmining_silver = 62149
pet_skillpetmining_coal = 62150
pet_skillpetmining_gold = 62151
pet_skillpetmining_mithril = 62152
pet_skillpetmining_granite = 62153
pet_skillpetmining_adamantite = 62154
pet_skillpetmining_runite = 62155
pet_skillpetmining_amethyst = 62156
pet_skillpetmining_lovakite = 62157
pet_skillpetmining_elemental = 62158
pet_skillpetmining_daeyalt = 62159
pet_skillpetmining_lead = 62160
pet_skillpetmining_rubium = 62161
pet_skillpetmining_nickel = 62162
pet_skillpetthieving = 62163
pet_skillpetthieving_panda = 62164
pet_skillpetthieving_tanuki = 62165
pet_skillpetsailing = 62166
pet_skillpetfarming = 62167
pet_skillpetfarming_crystal = 62168
pet_skillpetfarming_dragon = 62169
pet_skillpetfarming_herb = 62170
pet_skillpetfarming_lily = 62171
pet_skillpetfarming_redwood = 62172
pet_abyssalpet = 62173
pet_bloodhound_pet = 62174
pet_chompybird_pet = 62175
pet_herbiboarpet = 62176
pet_soulwarspet_blue = 62177
pet_soulwarspet_red = 62178
pet_penancepet = 62179
pet_quetzalpet = 62180
pet_goatpitpet = 62181
cat_kittenobject = 62182
cat_kittenobject_light = 62183
cat_kittenobject_brown = 62184
cat_kittenobject_black = 62185
cat_kittenobject_browngrey = 62186
cat_kittenobject_bluegrey = 62187
cat_kittenobject_hell = 62188
cat_growncatobject = 62189
cat_growncatobject_light = 62190
cat_growncatobject_brown = 62191
cat_growncatobject_black = 62192
cat_growncatobject_browngrey = 62193
cat_growncatobject_bluegrey = 62194
cat_growncatobject_hell = 62195
cat_overgrowncatobject = 62196
cat_overgrowncatobject_light = 62197
cat_overgrowncatobject_brown = 62198
cat_overgrowncatobject_black = 62199
cat_overgrowncatobject_browngrey = 62200
cat_overgrowncatobject_bluegrey = 62201
cat_overgrowncatobject_hell = 62202
cat_wileycatobject = 62203
cat_wileycatobject_light = 62204
cat_wileycatobject_brown = 62205
cat_wileycatobject_black = 62206
cat_wileycatobject_browngrey = 62207
cat_wileycatobject_bluegrey = 62208
cat_wileycatobject_hell = 62209
cat_lazycatobject = 62210
cat_lazycatobject_light = 62211
cat_lazycatobject_brown = 62212
cat_lazycatobject_black = 62213
cat_lazycatobject_browngrey = 62214
cat_lazycatobject_bluegrey = 62215
cat_lazycatobject_hell = 62216
pet_morph_baby_mole_mole_claw = 62217
pet_morph_baby_mole_mole_skin = 62218
pet_morph_rocky_redberries = 62219
pet_morph_rocky_poisonivy_berries = 62220
pet_morph_rocky_white_berries = 62221
pet_morph_tangleroot_guam_seed = 62222
pet_morph_tangleroot_dragonfruit_tree_seed = 62223
pet_morph_tangleroot_redwood_tree_seed = 62224
pet_morph_tangleroot_white_lily_seed = 62225
pet_morph_tangleroot_crystal_tree_seed = 62226
pet_morph_tangleroot_acorn = 62227
pet_morph_rock_golem_rock = 62228
pet_morph_rock_golem_tin_ore = 62229
pet_morph_rock_golem_copper_ore = 62230
pet_morph_rock_golem_iron_ore = 62231
pet_morph_rock_golem_blurite_ore = 62232
pet_morph_rock_golem_silver_ore = 62233
pet_morph_rock_golem_coal = 62234
pet_morph_rock_golem_gold_ore = 62235
pet_morph_rock_golem_mithril_ore = 62236
pet_morph_rock_golem_enakh_granite_tiny = 62237
pet_morph_rock_golem_enakh_granite_small = 62238
pet_morph_rock_golem_enakh_granite_medium = 62239
pet_morph_rock_golem_adamantite_ore = 62240
pet_morph_rock_golem_runite_ore = 62241
pet_morph_rock_golem_amethyst = 62242
pet_morph_rock_golem_lovakite_ore = 62243
pet_morph_rock_golem_elemental_workshop_ore = 62244
pet_morph_rock_golem_sang_jas_ore = 62245
pet_morph_rock_golem_lead_ore = 62246
pet_morph_rock_golem_rubium_splinters = 62247
pet_morph_rock_golem_nickel_ore = 62248
pet_morph_beaver_forestry_funky_shaped_log = 62249
pet_morph_beaver_forestry_fox_pet_whistle = 62250
pet_morph_beaver_forestry_pheasant_pet_egg = 62251
pet_morph_beaver_logs = 62252
pet_morph_beaver_oak_logs = 62253
pet_morph_beaver_willow_logs = 62254
pet_morph_beaver_maple_logs = 62255
pet_morph_beaver_yew_logs = 62256
pet_morph_beaver_magic_logs = 62257
pet_morph_beaver_redwood_logs = 62258
pet_morph_beaver_teak_logs = 62259
pet_morph_beaver_mahogany_logs = 62260
pet_morph_beaver_arctic_pine_log = 62261
pet_morph_beaver_camphor_logs = 62262
pet_morph_beaver_ironwood_logs = 62263
pet_morph_beaver_jatoba_logs = 62264
pet_morph_beaver_rosewood_logs = 62265
pet_morph_giant_squirrel_dark_acorn = 62266
pet_morph_giant_squirrel_calcified_acorn = 62267
pet_morph_phoenix_gnomish_firelighter_blue = 62268
pet_morph_phoenix_gnomish_firelighter_green = 62269
pet_morph_phoenix_trail_gnomish_firelighter_purple = 62270
pet_morph_phoenix_trail_gnomish_firelighter_white = 62271
pet_morph_sraracha_hosdun_orange_egg_sac = 62272
pet_morph_sraracha_hosdun_blue_egg_sac = 62273
pet_morph_muphin_muspah_pet_morph = 62274
pet_morph_nid_araxxor_pet_morph = 62275
pet_morph_lil_zik_tob_hardmode_dust = 62276
pet_morph_olmlet_raids_challenge_morph = 62277
pet_morph_little_nightmare_nightmare_challenge_morph = 62278
pet_morph_tumeken_s_guardian_toa_pet_morph_wardens = 62279
pet_morph_tumeken_s_guardian_toa_pet_morph_akkha = 62280
pet_morph_tumeken_s_guardian_toa_pet_morph_baba = 62281
pet_morph_tumeken_s_guardian_toa_pet_morph_kephri = 62282
pet_morph_tumeken_s_guardian_toa_pet_morph_zebak = 62283
pet_morph_rift_guardian_guardians_eye = 62284
dog_labrador_yellow = 62290
dog_labrador_brown = 62291
dog_labrador_black = 62292
dog_pug_fawn = 62293
dog_pug_black = 62294
dog_pug_brown = 62295
dog_spaniel_red = 62296
dog_spaniel_white = 62297
dog_spaniel_black = 62298
dog_shepard_toasted = 62299
dog_shepard_merle = 62300
dog_shepard_choco = 62301
dog_collie_bw = 62302
dog_collie_choco = 62303
dog_collie_merle = 62304
dog_chihuahua_tan = 62305
dog_chihuahua_toasted = 62306
dog_chihuahua_white = 62307
dog_corgi_tan = 62308
dog_corgi_toasted = 62309
dog_corgi_yellow = 62310
dog_greyhound_grey = 62311
dog_greyhound_cream = 62312
dog_greyhound_tan = 62313
dog_husky_bw = 62314
dog_husky_choco = 62315
dog_husky_grey = 62316
dog_samoyed_white = 62317
dog_samoyed_yellow = 62318
dog_samoyed_black = 62319
dog_shiba_tan = 62320
dog_shiba_toasted = 62321
dog_shiba_white = 62322
dog_yorkie_brown = 62323
dog_yorkie_white = 62324
dog_yorkie_yellow = 62325
pet_skilling_fishing = 62326
pet_skilling_mining = 62327
pet_skilling_woodcutting = 62328
pet_drop_mad_angel = 62329
pet_drop_mad_angel_quest = 62330
pet_drop_mole_giant = 62331
pet_drop_cowboss = 62332
pet_drop_callisto = 62333
pet_drop_callisto_singles = 62334
pet_drop_inferno_tzkalzuk_placeholder = 62335
pet_drop_kalphite_flyingqueen = 62336
pet_drop_maggot_king = 62337
pet_drop_nex = 62338
pet_drop_gargboss_dusk_phase4 = 62339
pet_drop_dagcave_magic_boss = 62340
pet_drop_dagcave_melee_boss = 62341
pet_drop_dagcave_ranged_boss = 62342
pet_drop_corp_beast = 62343
pet_drop_slayer_kraken_boss = 62344
pet_drop_smoke_devil_boss = 62345
pet_drop_snakeboss_boss_ranged = 62346
pet_drop_snakeboss_boss_melee = 62347
pet_drop_snakeboss_boss_magic = 62348
pet_drop_cata_boss = 62349
pet_drop_zalcano = 62350
pet_drop_tzhaar_fightcave_swarm_boss = 62351
pet_drop_venenatis = 62352
pet_drop_venenatis_singles = 62353
pet_drop_vetion_2 = 62354
pet_drop_vetion_2_single = 62355
