[gamevals.varp]
falador_makeover = 64850

[gamevals.varbit]
falador_makeover_active = 64850
falador_makeover_original_kit = 64851
falador_makeover_original_colour = 64852

[gamevals.synth]
varrock_fence_jump = 2461
