[[varn]]
id = "varn.lastcombat"

[[varn]]
id = "varn.aggressive_player"

[[varn]]
id = "varn.generic_state_2"

[[varn]]
id = "varn.attacking_player"

[[varn]]
id = "varn.lastattack"

[[varn]]
id = "varn.flat_armour"

[[varn]]
id = "varn.immune_melee"

[[varn]]
id = "varn.immune_ranged"

[[varn]]
id = "varn.immune_magic"

[[varn]]
id = "varn.gorilla_protect_damage"

[[varn]]
id = "varn.gorilla_protect_hits"

[[varn]]
id = "varn.gorilla_miss_streak"

[[varn]]
id = "varn.gorilla_protect_switching"

[[varn]]
id = "varn.td_shield_up"

[[varn]]
id = "varn.td_overhead_style"

[[varn]]
id = "varn.guaranteed_hit"

[[varn]]
id = "varn.venenatis_attacks"

[[varn]]
id = "varn.awakened_state"

[[varn]]
id = "varn.muspah_damage_since_switch"

[[varn]]
id = "varn.skip_killcount"

[[varn]]
id = "varn.muspah_melee_still_ticks"

[[varn]]
id = "varn.duke_flare_attacks"

[[varn]]
id = "varn.duke_flare_threshold"

[[varn]]
id = "varn.duke_after_gaze"

[[varn]]
id = "varn.callisto_roars"

[[varn]]
id = "varn.poison_severity"

[[varn]]
id = "varn.freeze_end_clock"

[[varn]]
id = "varn.freeze_immunity_end_clock"

[[varn]]
id = "varn.freeze_guaranteed"

[[varn]]
id = "varn.leviathan_volley_stage"

[[varn]]
id = "varn.leviathan_volleys"

[[varn]]
id = "varn.leviathan_stuns"

[[varn]]
id = "varn.leviathan_stunned"

[[varn]]
id = "varn.leviathan_in_special"

[[varn]]
id = "varn.leviathan_next_special"

[[varn]]
id = "varn.leviathan_stun_bearing"

[[varn]]
id = "varn.muspah_hits_since_switch"

[[varn]]
id = "varn.muspah_special_cooldown_end"

[[varn]]
id = "varn.muspah_final_triggered"

[[varn]]
id = "varn.muspah_shield_broken"

[[varn]]
id = "varn.muspah_shield_hp"

[[varn]]
id = "varn.muspah_pre_shield_hp"

[[varn]]
id = "varn.muspah_pre_shield_max_hp"

[[varn]]
id = "varn.muspah_final_attacks"

[[varn]]
id = "varn.muspah_shield_corrupted"

[[varn]]
id = "varn.vardorvis_next_head_gaze"

[[varn]]
id = "varn.vardorvis_strangle_ready_at"

[[varn]]
id = "varn.vardorvis_next_axes"

[[varn]]
id = "varn.td_damage_since_swap"

[[varn]]
id = "varn.td_first_hit_taken"

[[varn]]
id = "varn.td_defenceless"

[[varn]]
id = "varn.td_defenceless_at"

[[varn]]
id = "varn.dark_lure_end_clock"
