[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_14_16"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_18_52"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_27_30"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_35_7"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_43_53"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_48_16"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_51_43"

[[spawn]]
npc = "npc.wbr_bear"
coords = "0_52_160_5_29"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_10_42"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_11_18"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_19_11"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_21_25"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_29_54"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_29_8"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_30_37"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_32_46"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_37_27"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_40_8"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_41_53"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_45_22"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_47_49"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_52_21"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_53_25"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_54_38"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_7_24"

[[spawn]]
npc = "npc.wbr_cave_poisonspider"
coords = "0_52_160_8_37"


[[spawn]]
npc = "npc.venenatis_singles"
coords = "2_25_180_29_26"

[[spawn]]
npc = "npc.venenatis"
coords = "2_53_159_29_26"

[[spawn]]
npc = "npc.callisto_singles"
coords = "0_27_180_28_18"

[[spawn]]
npc = "npc.callisto"
coords = "0_52_161_31_24"
