package org.rsmod.content.areas.city.grandexchange

/** The market guide lists as printed on the wiki pages of the five experts. */
internal object WikiGuides {
    val ores =
        listOf(
            "Copper ore",
            "Tin ore",
            "Iron ore",
            "Silver ore",
            "Lead ore",
            "Gold ore",
            "Mithril ore",
            "Adamantite ore",
            "Nickel ore",
            "Runite ore",
            "Coal",
            "Clay",
            "Bronze bar",
            "Iron bar",
            "Steel bar",
            "Silver bar",
            "Lead bar",
            "Gold bar",
            "Mithril bar",
            "Adamantite bar",
            "Cupronickel bar",
            "Runite bar",
            "Uncut sapphire",
            "Sapphire",
            "Uncut emerald",
            "Emerald",
            "Uncut ruby",
            "Ruby",
            "Uncut diamond",
            "Diamond",
            "Uncut dragonstone",
            "Dragonstone",
            "Uncut onyx",
            "Onyx",
            "Uncut zenyte",
            "Zenyte",
        )

    val logs =
        listOf(
            "Logs",
            "Achey tree logs",
            "Oak logs",
            "Willow logs",
            "Teak logs",
            "Maple logs",
            "Mahogany logs",
            "Arctic pine logs",
            "Yew logs",
            "Camphor logs",
            "Magic logs",
            "Ironwood logs",
            "Redwood logs",
            "Rosewood logs",
        )

    val herbsAndPotions =
        listOf(
            "Vial",
            "Vial of water",
            "Grimy guam leaf",
            "Guam leaf",
            "Grimy marrentill",
            "Marrentill",
            "Grimy tarromin",
            "Tarromin",
            "Grimy harralander",
            "Harralander",
            "Grimy ranarr weed",
            "Ranarr weed",
            "Grimy toadflax",
            "Toadflax",
            "Grimy irit leaf",
            "Irit leaf",
            "Grimy avantoe",
            "Avantoe",
            "Grimy kwuarm",
            "Kwuarm",
            "Grimy snapdragon",
            "Snapdragon",
            "Grimy cadantine",
            "Cadantine",
            "Grimy lantadyme",
            "Lantadyme",
            "Grimy dwarf weed",
            "Dwarf weed",
            "Grimy torstol",
            "Torstol",
            "Grimy huasca",
            "Huasca",
            "Elkhorn coral",
            "Pillar coral",
            "Umbral coral",
            "Haemostatic poultice",
            "Attack potion(4)",
            "Super attack(4)",
            "Strength potion(4)",
            "Super strength(4)",
            "Defence potion(4)",
            "Super defence(4)",
            "Restore potion(4)",
            "Super restore(4)",
            "Prayer potion(4)",
            "Agility potion(4)",
            "Combat potion(4)",
            "Super combat potion(4)",
            "Zamorak brew(4)",
            "Saradomin brew(4)",
            "Ancient brew(4)",
            "Menaphite remedy(4)",
            "Antifire potion(4)",
            "Extended antifire(4)",
            "Super antifire potion(4)",
            "Extended super antifire(4)",
            "Energy potion(4)",
            "Super energy(4)",
            "Extreme energy potion(4)",
            "Stamina potion(4)",
            "Extended stamina potion(4)",
            "Weapon poison",
            "Weapon poison(+)",
            "Weapon poison(++)",
            "Antipoison(4)",
            "Superantipoison(4)",
            "Antidote+(4)",
            "Antidote++(4)",
            "Anti-venom(4)",
            "Anti-venom+(4)",
            "Extended anti-venom+(4)",
            "Ranging potion(4)",
            "Magic potion(4)",
            "Hunter potion(4)",
            "Super hunter potion(4)",
            "Fishing potion(4)",
            "Super fishing potion(4)",
            "Combat potion set",
            "Super potion set",
            "Bastion potion(4)",
            "Divine bastion potion(4)",
            "Battlemage potion(4)",
            "Divine battlemage potion(4)",
            "Divine super combat potion(4)",
            "Divine super attack potion(4)",
            "Divine super strength potion(4)",
            "Divine super defence potion(4)",
            "Divine ranging potion(4)",
            "Divine magic potion(4)",
        )

    val runes =
        listOf(
            "Rune essence",
            "Pure essence",
            "Fire rune",
            "Water rune",
            "Air rune",
            "Earth rune",
            "Mind rune",
            "Body rune",
            "Death rune",
            "Nature rune",
            "Chaos rune",
            "Law rune",
            "Cosmic rune",
            "Blood rune",
            "Soul rune",
            "Astral rune",
            "Wrath rune",
            "Mist rune",
            "Dust rune",
            "Smoke rune",
            "Mud rune",
            "Steam rune",
            "Lava rune",
            "Aether rune",
        )

    val weaponsAndArmour =
        listOf(
            "Adamant set (lg)",
            "Adamant set (sk)",
            "Rune armour set (lg)",
            "Rune armour set (sk)",
            "Dragon armour set (lg)",
            "Dragon armour set (sk)",
            "Dragon med helm",
            "Dragon full helm",
            "Dragon chainbody",
            "Dragon platebody",
            "Dragon platelegs",
            "Dragon plateskirt",
            "Dragon boots",
            "Dragon 2h sword",
            "Dragon sq shield",
            "Dragon kiteshield",
            "Green dragonhide set",
            "Black dragonhide set",
            "Ahrim's armour set",
            "Dharok's armour set",
            "Guthan's armour set",
            "Karil's armour set",
            "Torag's armour set",
            "Verac's armour set",
            "Abyssal whip",
            "Kraken tentacle",
            "Dark bow",
            "Dragon scimitar",
            "Dragon axe",
            "Dragon pickaxe",
            "Dragon warhammer",
            "Dragon sword",
            "Dragon claws",
            "Granite maul",
            "Uncharged trident",
            "Uncharged trident (e)",
            "Uncharged toxic trident",
            "Uncharged toxic trident (e)",
            "Odium ward",
            "Malediction ward",
            "Armadyl crossbow",
            "Saradomin sword",
            "Armadyl godsword",
            "Bandos godsword",
            "Saradomin godsword",
            "Zamorak godsword",
            "Ancient godsword",
            "Armadyl helmet",
            "Bandos chestplate",
            "Armadyl chestplate",
            "Bandos tassets",
            "Armadyl chainskirt",
            "Bandos boots",
            "Eternal boots",
            "Pegasian boots",
            "Primordial boots",
            "Avernic treads",
            "Dragonfire shield",
            "Dragonfire ward",
            "Elysian spirit shield",
            "Spectral spirit shield",
            "Arcane spirit shield",
            "Toxic blowpipe (empty)",
            "Serpentine helm (uncharged)",
            "Staff of the Dead",
            "Toxic staff (uncharged)",
            "Dwarf cannon set",
            "Abyssal dagger",
            "Abyssal bludgeon",
            "Tome of Fire (empty)",
            "Imbued heart",
            "Twisted bow",
            "Twisted buckler",
            "Elder maul",
            "Kodai wand",
            "Dragon hunter crossbow",
            "Dinh's bulwark",
            "Ancestral hat",
            "Ancestral robe top",
            "Ancestral robe bottom",
            "Justiciar armour set",
            "Sanguinesti staff (uncharged)",
            "Ghrazi rapier",
            "Scythe of Vitur (uncharged)",
            "Inquisitor's armour set",
            "Inquisitor's mace",
            "Nightmare staff",
            "Zaryte vambraces",
            "Zaryte crossbow",
            "Torva full helm",
            "Torva platebody",
            "Torva platelegs",
            "Masori armour set (f)",
            "Osmumten's fang",
            "Tumeken's shadow (uncharged)",
            "Elidinis' ward",
            "Tonalztics of Ralos (uncharged)",
            "Sunfire fanatic armour set",
            "Oathplate armour set",
        )
}
