[[npc]]
isServerOnly = true
id = "npc.vmq1_alina"
inherit = "npc.vmq1_alina"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_noah"
inherit = "npc.vmq1_noah"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_sergeant"
inherit = "npc.vmq1_guard_sergeant"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_sergeant_roof"
inherit = "npc.vmq1_guard_sergeant_roof"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_itzla"
inherit = "npc.vmq1_itzla"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_knight_1_castle"
inherit = "npc.vmq1_knight_1_castle"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_knight_2_castle"
inherit = "npc.vmq1_knight_2_castle"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_1"
inherit = "npc.vmq1_guard_1"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_2"
inherit = "npc.vmq1_guard_2"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_3"
inherit = "npc.vmq1_guard_3"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_4"
inherit = "npc.vmq1_guard_4"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_5"
inherit = "npc.vmq1_guard_5"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_6"
inherit = "npc.vmq1_guard_6"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_7"
inherit = "npc.vmq1_guard_7"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_8"
inherit = "npc.vmq1_guard_8"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_9"
inherit = "npc.vmq1_guard_9"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_guard_10"
inherit = "npc.vmq1_guard_10"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bag_guard_varrock"
inherit = "npc.vmq1_bag_guard_varrock"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bandit_1_varrock"
inherit = "npc.vmq1_bandit_1_varrock"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bandit_2_varrock"
inherit = "npc.vmq1_bandit_2_varrock"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bandit_3_varrock"
inherit = "npc.vmq1_bandit_3_varrock"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bandit_4_varrock"
inherit = "npc.vmq1_bandit_4_varrock"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"

[[npc]]
isServerOnly = true
id = "npc.vmq1_bandit_4_cell"
inherit = "npc.vmq1_bandit_4_cell"
wanderRange = 0
defaultMode = "None"
moveRestrict = "NoMove"
