[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_progress"
varp = "varp.hazeelcultquest"
startBit = 0
endBit = 3

[[varp]]
isServerOnly = true
id = "varp.hazeel_cult_state"
scope = "Perm"
transmit = "Never"

[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_valve_1"
varp = "varp.hazeel_cult_state"
startBit = 0
endBit = 0

[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_valve_2"
varp = "varp.hazeel_cult_state"
startBit = 1
endBit = 1

[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_valve_3"
varp = "varp.hazeel_cult_state"
startBit = 2
endBit = 2

[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_valve_4"
varp = "varp.hazeel_cult_state"
startBit = 3
endBit = 3

[[varbit]]
isServerOnly = true
id = "varbit.hazeel_cult_valve_5"
varp = "varp.hazeel_cult_state"
startBit = 4
endBit = 4
