[[varbit]]
isServerOnly = true
id = "varbit.sheep_shearer_progress"
varp = "varp.sheep"
startBit = 0
endBit = 4

[[varp]]
isServerOnly = true
id = "varp.sheep_shearer_state"
scope = "Perm"
transmit = "Never"

[[varbit]]
isServerOnly = true
id = "varbit.sheep_shearer_thing_seen"
varp = "varp.sheep_shearer_state"
startBit = 0
endBit = 0
